# Install script for directory: /home/vboxuser/zephyrproject/zephyr

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

# Set path to fallback-tool for dependency-resolution.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/home/vboxuser/toolchains/riscv/bin/riscv64-unknown-elf-objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/zephyr/arch/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/zephyr/lib/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/zephyr/soc/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/zephyr/boards/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/zephyr/subsys/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/zephyr/drivers/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/acpica/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/cmsis/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/cmsis-dsp/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/cmsis-nn/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/cmsis_6/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/fatfs/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/adi/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_afbr/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_ambiq/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/atmel/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_bouffalolab/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_espressif/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_ethos_u/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_gigadevice/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_infineon/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_intel/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/microchip/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_nordic/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/nuvoton/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_nxp/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/openisa/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/quicklogic/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_renesas/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_rpi_pico/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_sifli/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_silabs/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_st/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_stm32/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_tdk/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_nmsis/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_telink/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/ti/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_wch/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hal_wurthelektronik/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/xtensa/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/hostap/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/liblc3/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/libmctp/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/libmetal/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/libsbc/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/littlefs/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/lora-basics-modem/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/loramac-node/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/lvgl/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/mbedtls/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/mcuboot/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/mipi-sys-t/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/nanopb/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/nrf_wifi/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/open-amp/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/openthread/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/percepio/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/picolibc/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/segger/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/trusted-firmware-a/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/trusted-firmware-m/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/uoscore-uedhoc/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/zcbor/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/modules/nrf_hw_models/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/zephyr/kernel/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/zephyr/cmake/flash/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/zephyr/cmake/usage/cmake_install.cmake")
  include("/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/zephyr/cmake/reports/cmake_install.cmake")

endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
if(CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "/home/vboxuser/zephyrproject/wasm-micro-runtime/product-mini/platforms/zephyr/thesis-example-fw/qemu_rv64_nmsis_opt/zephyr/install_local_manifest.txt"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
